/**
 * Convex Auth provider configuration.
 *
 * Convex reads this file at deploy time to know which providers/issuers
 * to trust. The actual provider runtime config lives in `auth.ts`; this
 * file just declares the JWT issuers Convex should accept tokens from.
 *
 * Convex Auth itself issues its own JWTs (`process.env.CONVEX_SITE_URL`
 * is the issuer). We register it here so the backend trusts its own
 * tokens.
 *
 * ──────────────────────────────────────────────────────────────────────
 * Required environment variables on the Convex deployment
 * (set with `npx convex env set <NAME> <value>`):
 *
 *  Common:
 *   CONVEX_SITE_URL                  (auto — Convex deployment URL)
 *   JWT_PRIVATE_KEY                  (auto — generated by `npx @convex-dev/auth`)
 *   JWKS                             (auto — generated by `npx @convex-dev/auth`)
 *
 *  Apple Sign-In (https://developer.apple.com → Certificates):
 *   AUTH_APPLE_ID                    Services ID, e.g. "com.weightcutwizard.web"
 *   AUTH_APPLE_SECRET                Client secret JWT — Convex Auth will
 *                                    build this from the p8 key on your
 *                                    behalf if you supply:
 *   AUTH_APPLE_TEAM_ID               Apple Developer Team ID (10 chars)
 *   AUTH_APPLE_KEY_ID                Sign-in-with-Apple Key ID (10 chars)
 *   AUTH_APPLE_PRIVATE_KEY           Contents of the .p8 file (PEM)
 *
 *  Password reset email (Resend or similar — Phase-3 TODO):
 *   AUTH_RESEND_KEY                  Resend API key (optional for now —
 *                                    the Password provider's `reset` flow
 *                                    will throw until this is wired up.)
 * ──────────────────────────────────────────────────────────────────────
 */
export default {
  providers: [
    {
      // The Convex deployment is its own JWT issuer.
      domain: process.env.CONVEX_SITE_URL,
      applicationID: "convex",
    },
  ],
};
